#!/usr/bin/env bash
set -ex

ARCHS=(
  amd64
  arm64
)
OSES=(
  # linux
  # darwin
  windows
)

cp package.json internal/
NAME=$(cat package.json | jq --raw-output .name)

for os in "${OSES[@]}"; do
  for arch in "${ARCHS[@]}"; do
    LDFLAGS="-s -w"
    if [[ "$os" == "windows" ]]; then
      LDFLAGS="$LDFLAGS -H=windowsgui"
    fi

    GOOS="$os" GOARCH="$arch" go build -ldflags "$LDFLAGS" -o "dist/$NAME-$os-$arch" ./cmd/sisr-remote-helper.go
  done
done

find ./dist -name '*-windows-*' -not -name '*.exe' | while read -r line; do
  mv "$line" "$line.exe"
done
